TauID_eff:
  data_file:
    sample_name: ggH_htt
    path: tauID_eff.root
    tree_path: "Events"
  variables:
    genTau:
      - name: pt
        x_range: [15.0, 500.0001]
        bins: [18.0, 20.0, 22.0, 24.0, 26.0, 28.0, 30.0, 35.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0, 150.0, 200.0, 500.0, 1000.0, 5000.0]
      - name: eta
        x_range: [-2.6001, 2.6001]
        bins: [-2.4, -2.2, -2.0, -1.8, -1.6, -1.4, -1.2, -1.0, -0.8, -0.6, -0.4, -0.2, 0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4]
      - name: phi
        x_range: [-3.2001, 3.2001]
        bins: [-3.2, -2.8, -2.4, -2.0, -1.6, -1.2, -0.8, -0.4, 0.0, 0.4, 0.8, 1.2, 1.6, 2.0, 2.4, 2.8, 3.2]
    recoTau:
      - name: rawIso
        x_range: [0, 10.0001]
        bins: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.0, 94.0, 95.0, 96.0, 97.0, 98.0, 99.0]
    other:
      - name: Pileup_nTrueInt
        x_range: [50, 80]
        bins: [52, 55, 58, 61, 64, 67, 70, 73, 76, 79]
  denominators:
    Base: "pt > 20 && |eta| < 2.3"
  numerators:
    Base: "pt > 20 && |eta| < 2.3"
    idIso:
      Loose: "idIso > 0.5"
      Medium: "idIso > 1.5"
      Tight: "idIso > 3.5"
    idChargedIso:
      Loose: "idChargedIso > 0.5"
      Medium: "idChargedIso > 1.5"
      Tight: "idChargedIso > 3.5"
    idDecayModeNewDMs:
      Default: "idDecayModeNewDMs > 0.5"
    firstNum:
      Default: idLeadTkFinding > 0.5
    secondNum:
      Default: "idLeadTkFinding > 0.5 && idDecayModeNewDMs > 0.5"
    thirdNum:
      Loose: "idLeadTkFinding > 0.5 && idChargedIso > 0.5"
      Medium: "idLeadTkFinding > 0.5 && idChargedIso > 1.5"
      Tight: "idLeadTkFinding > 0.5 && idChargedIso > 3.5"
    fourthNum:
      Loose: "idLeadTkFinding > 0.5 && idDecayModeNewDMs > 0.5 && idChargedIso > 0.5"
      Medium: "idLeadTkFinding > 0.5 && idDecayModeNewDMs > 0.5 && idChargedIso > 1.5"
      Tight: "idLeadTkFinding > 0.5 && idDecayModeNewDMs > 0.5 && idChargedIso > 3.5"
    fifthNum:
      Loose: "idLeadTkFinding > 0.5 && idIso > 0.5"
      Medium: "idLeadTkFinding > 0.5 && idIso > 1.5"
      Tight: "idLeadTkFinding > 0.5 && idIso > 3.5"
    sixthNum:
      Loose: "idLeadTkFinding > 0.5 && idDecayModeNewDMs > 0.5 && idIso > 0.5"
      Medium: "idLeadTkFinding > 0.5 && idDecayModeNewDMs > 0.5 && idIso > 1.5"
      Tight: "idLeadTkFinding > 0.5 && idDecayModeNewDMs > 0.5 && idIso > 3.5"

